### ISSUE TITLE
button(paper-button): stylize

### ISSUE THREAD

**Issue by nazartokar** [advanced-rest-client/api-console-app#11]
### Description
Stylize `paper-button`: try it, `hide/show` toggle.

### Live Demo
[Example](http://localhost:8080/docs/resources-1-methods-0?api=https://cdn.rawgit.com/advanced-rest-client/drive-raml-api-v2/ab60ed28/api.raml)

### Screenshots

![screenshot 2017-04-18 11 36 40](https://cloud.githubusercontent.com/assets/7399928/25124210/5a049e48-242b-11e7-8608-b474a0ef4149.png)
![screenshot 2017-04-18 11 36 42](https://cloud.githubusercontent.com/assets/7399928/25124211/5a0aff04-242b-11e7-863b-fcf0fde6a034.png)

**Comment by jarrodek** [comment]
To style all buttons we need following mixins and variables:
```
--paper-button: {
    @apply(--anypoint-font-body);
    border-radius: 0;
    box-shadow: none;
    padding: 10px 16px;
    box-sizing: border-box;
    text-transform: none;
  };
--paper-button-ink-color: transparent;
```

We don't need to create our own `paper-button` nor we should define one. Elements require paper-button and will download and register it. This will case an error when trying to register an element that already exists.

**Comment by jarrodek** [comment]
To previous code I forgot about:
```
html {
  font-size: 65%;
}
```
For now it is necessary because font sizes in the [typography](https://github.com/advanced-rest-client/anypoint-styles/blob/master/typography.html) are defined in `rem` units. That was the only font definitions I have found earlier in our UX pages. However this should be changed to pixels.

**Comment by jarrodek** [comment]
The toggle view button will require a change to `raml-docs-resource-viewer` because there's no CSS mixin applied to toggle buttons to add a border.

Where's an example of this button in Anypoint platform components? I couldn't find it. Also I believe it at most should be a holo [ActionButton](http://ux.mulesoft.com/#/playground/ActionButton) with border only.

**Comment by jarrodek** [comment]
About previous comment: I was mistaken the section toggle button with type schema toggle button. You are right. It should be with border and label. Toggle button for the code section should be an action button.
