### ISSUE TITLE
When multiple schemes are defined there's no way to select one of them

### ISSUE THREAD

**Issue by carobazan** [advanced-rest-client/api-console-app#7]
### Description
When having multiple security schemas no information is displayed, the two security schemes info should appear in different tabs or something similar. When using try it, in the Authorization tab, the combo does not show the options correctly either

### Expected outcome
Information of authorizations available should be shown and a combo should allow user to select one of the authorization schemes

### Actual outcome
No info is display about authorization, try it only allows to select one of the options

### Steps to reproduce
1. Open api attached in new console -[testSecurity.zip](https://github.com/advanced-rest-client/api-console-app/files/925768/testSecurity.zip)
2. select resource /testSecuredByOauth2Multiple or /testSecuredByNullOrBasic
3. Check info displayed and click on Try it
4. On try it page try to choose one to the 2 authorizations
Only one option is shown

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by jarrodek** [comment]
This is expected behavior.

The authorization panel that is controlling this behavior selects first available security scheme on behalf of the user. Because some methods requires several steps (oauth1, oauth2) there's a stepper in the UI that hides previous step.

User can change previous step(s) by clicking on it's header. Then the full step will be visible.
Because security schemes can have complicated structures this behavior won't change.

**Comment by jarrodek** [comment]
Although, there's should be an indication - possibly on hover action. Like an edit button.

**Comment by jarrodek** [comment]
The "edit" icon has been added to the element's title when hovering the title as an indication to make an action.
